---

openshift_release: "{{ openshift_release }}"
openshift_version: "{{ openshift_release }}"
openshift_clusterid: "{{ cluster_id }}"
openshift_aws_region: "{{aws_region}}"
openshift_deployment_type: origin

docker_upgrade: true
docker_storage_driver: devicemapper
openshift_docker_additional_registries: registry.access.redhat.com
openshift_disable_check: memory_availability,docker_image_availability,docker_storage

openshift_clock_enabled: true
openshift_use_openshift_sdn: true
os_sdn_network_plugin_name: redhat/openshift-ovs-multitenant
os_firewall_enabled: true

openshift_master_cluster_method: native
openshift_master_cluster_hostname: "master.{{ openshift_domain }}"
openshift_master_cluster_public_hostname: "console.{{ openshift_domain }}"
openshift_master_default_subdomain: "apps.{{ openshift_domain }}"
openshift_master_console_port: 443
openshift_master_api_port: 443
openshift_master_dynamic_provisioning_enabled: true

openshift_master_identity_providers:
- name: github
  login: true
  challenge: false
  kind: GitHubIdentityProvider
  client_id: "{{ github_client_id }}"
  client_secret: "{{ github_client_secret }}"
  organizations:
  - "{{ github_orgs | default(null) }}"

openshift_hosted_selector: {"svc": "infra"}
openshift_hosted_router_selector: 'svc=router'
openshift_registry_selector: 'svc=infra'
openshift_metrics_hawkular_nodeselector: "{{ openshift_hosted_selector }}"
openshift_metrics_cassandra_nodeselector: "{{ openshift_hosted_selector }}"
openshift_metrics_heapster_nodeselector: "{{ openshift_hosted_selector }}"

openshift_hosted_manage_registry: true
openshift_hosted_registry_storage_kind: object
openshift_hosted_registry_storage_provider: s3
openshift_hosted_registry_storage_s3_accesskey: "{{ aws_access_key }}"
openshift_hosted_registry_storage_s3_secretkey: "{{ aws_secret_key }}"
openshift_hosted_registry_storage_s3_bucket: "datastore.{{ openshift_domain }}"
openshift_hosted_registry_storage_s3_region: "{{ aws_region }}"
openshift_hosted_registry_storage_s3_chunksize: 26214400
openshift_hosted_registry_storage_s3_rootdirectory: /registry
openshift_hosted_registry_pullthrough: true
openshift_hosted_registry_acceptschema2: true
openshift_hosted_registry_enforcequota: true
# TODO: temp fix, remove later
openshift_hosted_registry_images: 'openshift/origin-docker-registry:v3.6.1'
openshift_hosted_registry_registryurl: "{{ openshift_hosted_registry_images }}"

openshift_metrics_install_metrics: true
openshift_metrics_deployer_version: "{{ openshift_image_tag }}"
openshift_metrics_upgrade: true
openshift_metrics_storage_kind: nfs
openshift_metrics_storage_host: "nas.{{ openshift_domain }}"
openshift_metrics_storage_access_modes:
- ReadWriteOnce
openshift_metrics_storage_nfs_directory: /exports
openshift_metrics_storage_nfs_options: '*(rw,root_squash)'
openshift_metrics_storage_volume_name: metrics
openshift_metrics_storage_volume_size: 20Gi

openshift_logging_install_logging: false
openshift_hosted_prometheus_deploy: false
openshift_enable_service_catalog: false
openshift_management_install_management: false
openshift_examples_load_db_templates: false
openshift_examples_load_quickstarts: false

g_all_hosts: "{{ groups['tag_clusterid_' ~ cluster_id] | default([]) | intersect(groups['tag_environment_' ~ cluster_env] | default([])) }}"
g_etcd_hosts: "{{ g_all_hosts | intersect(groups['tag_host_type_etcd'] | default([])) }}"
g_lb_hosts: "{{ g_all_hosts | intersect(groups['tag_host_type_lb'] | default([])) }}"
g_nfs_hosts: "{{ g_all_hosts | intersect(groups['tag_host_type_nfs'] | default([])) }}"
g_master_hosts: "{{ g_all_hosts | intersect(groups['tag_host_type_master'] | default([])) }}"
g_node_hosts: "{{ g_all_hosts | intersect(groups['tag_host_type_node'] | default([])) }}"
g_infra_hosts: "{{ g_node_hosts | intersect(groups['tag_sub_host_type_infra'] | default([])) }}"
g_compute_hosts: "{{ g_node_hosts | intersect(groups['tag_sub_host_type_compute'] | default([])) }}"
g_glusterfs_hosts: "{{ g_node_hosts | intersect(groups['tag_sub_host_type_glusterfs'] | default([])) }}"
g_nodeonmaster: true
