---

openshift_release: "{{ openshift_release }}"
openshift_version: "{{ openshift_release }}"
openshift_image_tag: "v{{ openshift_release }}"
openshift_pkg_version: "-{{ openshift_release }}"
openshift_cluster_id: "{{ cluster_id }}"
deployment_type: origin

cli_openshift_master_cluster_method: native
cli_use_openshift_sdn: true
cli_sdn_network_plugin_name: redhat/openshift-ovs-multitenant
cli_openshift_use_dnsmasq: true

openshift_clock_enabled: true
openshift_use_openshift_sdn: "{{ cli_use_openshift_sdn }}"
os_sdn_network_plugin_name: "{{ cli_sdn_network_plugin_name }}"
docker_upgrade: true
os_firewall_enabled: true
enable_excluders: false
etcd_is_thirdparty: false

openshift_master_cluster_method: "{{ cli_openshift_master_cluster_method }}"
openshift_master_cluster_hostname: "master.{{ openshift_domain }}"
openshift_master_cluster_public_hostname: "dashboard.{{ openshift_domain }}"
openshift_master_default_subdomain: "apps.{{ openshift_domain }}"
openshift_master_console_port: 443
openshift_master_api_port: 443
openshift_master_session_name: ssn
openshift_master_session_max_seconds: 3600
openshift_master_dynamic_provisioning_enabled: true
openshift_use_dnsmasq: "{{ cli_openshift_use_dnsmasq }}"

openshift_master_identity_providers:
- name: github
  login: true
  challenge: false
  kind: GitHubIdentityProvider
  client_id: "{{ github_client_id }}"
  client_secret: "{{ github_client_secret }}"
  organizations:
  - "{{ github_orgs | default(null) }}"

openshift_cloudprovider_kind: aws
openshift_cloudprovider_aws_access_key: "{{ aws_access_key }}"
openshift_cloudprovider_aws_secret_key: "{{ aws_secret_key }}"

cli_ec2_region: "{{ hostvars[inventory_hostname]['ec2_tag_region'] }}"
openshift_hosted_router_selector: 'svc=router'
openshift_hosted_registry_selector: 'svc=master'
openshift_metrics_hawkular_nodeselector: 'svc=master'
openshift_metrics_cassandra_nodeselector: 'svc=master'
openshift_metrics_heapster_nodeselector: 'svc=master'

openshift_hosted_manage_registry: true
openshift_hosted_registry_storage_kind: object
openshift_hosted_registry_storage_provider: s3
openshift_hosted_registry_storage_s3_accesskey: "{{ aws_access_key }}"
openshift_hosted_registry_storage_s3_secretkey: "{{ aws_secret_key }}"
openshift_hosted_registry_storage_s3_bucket: "datastore.{{ openshift_domain }}"
openshift_hosted_registry_storage_s3_region: "{{ aws_region }}"
openshift_hosted_registry_storage_s3_chunksize: 26214400
openshift_hosted_registry_storage_s3_rootdirectory: /registry
openshift_hosted_registry_pullthrough: true
openshift_hosted_registry_acceptschema2: true
openshift_hosted_registry_enforcequota: true

openshift_hosted_metrics_deploy: true
openshift_hosted_metrics_upgrade: true
openshift_hosted_metrics_storage_kind: nfs
openshift_hosted_metrics_storage_host: "nas.{{ openshift_domain }}"
openshift_hosted_metrics_storage_access_modes:
- ReadWriteOnce
openshift_hosted_metrics_storage_nfs_directory: /exports
openshift_hosted_metrics_storage_nfs_options: '*(rw,root_squash)'
openshift_hosted_metrics_storage_volume_name: metrics
openshift_hosted_metrics_storage_volume_size: 20Gi

openshift_hosted_logging_deploy: false

openshift_examples_load_db_templates: false
openshift_examples_load_quickstarts: false
