---

containerized: true
etcd_is_containerized: true
openshift_node_labels:
  region: "{{ hostvars[inventory_hostname]['ec2_tag_region'] }}"
  type: "{{ hostvars[inventory_hostname]['ec2_tag_sub-host-type'] }}"
  svc: "{{ hostvars[inventory_hostname]['ec2_tag_svc'] }}"
