---

# https://github.com/openshift/openshift-ansible/issues/2206
openshift_schedulable: true
containerized: true
g_nodeonmaster: true
openshift_node_labels:
  region: "{{ hostvars[inventory_hostname]['ec2_tag_region'] }}"
  type: "{{ hostvars[inventory_hostname]['ec2_tag_sub_host_type'] }}"
  svc: "{{ hostvars[inventory_hostname]['ec2_tag_svc'] }}"
